1. Packed Blocks and VInt Blocks
    写.doc, .pos, .pay文件时，会对docId, freq, pos, payloadLen, payloadBytes, offsetStart, offsetLength数组做Packed Block和
VInt Block处理，即每处理128个文档，就将docId，freq数组打包成一个Packed Block，或每处理128个Prox，就将pos, payloadLen, payloadBytes,
offsetStart, offsetLength数组打包成一个PackedBlock。如果不足128个，就用VInt Block保存。这种方式保存这些数据主要是为了数据压缩，节省空间。
    payload, offset如果可以packed block，会保存在.pay文件。否则，以VInt Block的形式保存在.pos文件中。
    doc,pos,pay在field之间，以及term之间没有保存分割标志，每个field，term的开始fp保存在tim文件中。所以在读取阶段，先通过读取索引文件.tim来
得到在索引文件.doc,.pos,.pay的信息。
    详见Lucene90PostingsFormat类文档。
    注意：doc文件处理了128个doc可以packed block时，pos，pay文件不一定可以packed block。

2. .doc文件
    doc文件保存term的posting docId，freq 以及term的skipList，用于在doc,pos,pay文件的多个packed block间快速查询。
    a. singletonDocId
        对于df=1的term，docId和词频不会保存在doc文件中，而是保存在tip文件中。TODO wj
    b. 排序
        field，term都按字典序排序

3. SkipList
    skipList保存在.doc文件中，每个term有一个skipList，在处理完某个term时会写入该term的skipList数据。skipList主要是为了在查询某个term的
postings中某个docId的freq，pos，payload，offset时，能够快速在Packed Block间快速移动。如果term的posting列表不大于128，则不会生成skipList。
    skipList有两个参数：
        skipInterval: 每skipInterval个文档，将其写入到第0层。默认128
        skipMultiplier：对于第n层(n > 0)，n-1层每处理skipMultiplier个，将其写到第n层.默认8
    所以正常意义的skipInterval其实是skipMultiplier。
    除了第0层，其他层开始时都有length数据。
    每当处理128个doc，将docId，freq打包成一个Packed Block后，会将该Packed Block中的最后一个doc的下列信息写入SkipList：
        docSkip: docId delta, 与该层前一个docId的差值
        docFPSkip: 该doc Block下一个block在doc文件开始写入的FP delta，与该层前一个FP的delta
        posFPSkip: 下一个pos block在pos文件开始写入的FP，与该层前一个FP的delta
        posBlockOffset: 下一个pos block可能还在内存中，该值保存内存中pos buffer的下标，即当前内存中prox的个数
        sumPayLength: 内存中payloadBytes的大小，及内存中所有payload的大小只和
        payFPSkip: 下一个pay Block在pay文件开始写入的FP，与该层前一个FP的delta
        freqNorm: TODO wj
        childPointer：除了第0层，其他的skipData都有该字段，表示下一层中该节点的offset(FP)
    skipList的增长规则：
        每128个doc，会将最后一个doc的信息其写入到第0层
        如果currDoc = 128 * 8^k, 会将其写入到0, ... ,k层。
    查找时，docId要么在skipList中，要么不在。如果在，直接找到对应的block。如果不在，找到比其大的最近一个docId，其就在该Block中。
    示意图如下：
                                                d                                   (2 level)
                        d                       d           d                       (1 level)
            d           d           d           d           d           d           (0 level)
    d   d   d   d   d   d   d   d   d   d   d   d   d   d   d   d   d   d   d   d  （docId postings）
    skipInterval = 3, skipMultiplier = 2

@startuml
json ".doc File Layout \n 存储文档的倒排索引，如term的posting docId，freq 以及term的skipList" as J {
   "Header":[
      {"HeaderMagic\t": "[Int] 0x3fd76c17"},
      {"Codec\t\t": "[String] Lucene90PostingsWriterDoc"},
      {"Version\t\t": "[Int] 0"},
      {"Id\t\t\t": "[16 Bytes] random id"},
      {"SuffixLength\t": "[Byte] 0x0A"},
      {"Suffix\t\t": "[Bytes] Lucene90_0"}
   ],
   "Content":[
    {"FieldA\t": [
      {"Term1\t": [
         {"PackedBlock\t":[
            {"PackedDocDeltaBlock\t":[
               {"Token\t\t": "[Byte] (numEs << 5) | bitsRequired\t"},
               {"DocDeltas\t": "[Longs] bit packing"},
               {"Exceptions\t": "[Bytes] (eIdx, eInc) * numEs"}
            ]},
            {"PackedFreqBlock\t\t":[
              {"Token\t\t": "[Byte] (numEs << 5) | bitsRequired\t"},
              {"Freqs\t\t": "[Longs] bit packing"},
              {"Exceptions\t": "[Bytes] (eIdx, eInc) * numEs"}
            ]}
         ]},
         {"PackedBlock\t":["..."]},
         "...",
         {"VIntBlock\t\t":[
            {"VIntDocFreqBlock\t\t": [
               {"DocFreqPair\t": [
                  "[VInt] DocDeltaCode\t\t\t\t",
                  "[VInt] Freq"
               ]},
               "..."
            ]}
         ]}
      ]},
      {"SkipList1\t": [
         {"Level_n\t\t": [
            "[VLong] levelLength",
            {"skipDatas\t\t\t":[
               {"skipData\t\t":[
                  "[VInt] docSkip",
                  "[VLong] docFPSkip",
                  "[VLong] posFPSkip",
                  "[VInt] posBlockOffset\t\t\t\t",
                  "[VInt] payLength",
                  "[VLong] payFPSkip",
                  "[Bytes] freqNorm",
                  "[VLong] childPointer"
               ]},
               "..."
            ]
            }
         ]},
         {"Level_n-1\t": ["..."]},
         "...",
         {"Level_0\t\t": [
            {"skipDatas\t\t\t":[
               {"skipData\t\t":[
                  "[VInt] docSkip",
                  "[VLong] docFPSkip",
                  "[VLong] posFPSkip",
                  "[VInt] posBlockOffset\t\t\t\t",
                  "[VInt] payLength",
                  "[VLong] payFPSkip",
                  "[Bytes] freqNorm"
               ]},
               "..."
            ]
            }
         ]}
      ]},
      {"Term2\t": ["..."]},
      {"SkipList2\t": ["..."]},
      "..."
    ]},
    {"FieldB\t":["..."]},
    "..."
   ],
   "Footer":[
      {"FooterMagic\t": "[Int] 0xc02893e8"},
      {"Zero\t\t\t": "[Int] 0"},
      {"CRC\t\t\t": "[Long] crc"}
   ]
}
@enduml
