1. .tim文件（term dictionary, 词项字典）
    .tim文件保存term后缀，term统计（docFreq，totalTermFreq），term元数据（该term在doc，pos，pay文件开始的FP，
以及pos文件中VInt Block开始的FP，doc中skipList开始的offset）。所以在读取阶段，我们是先通过读取索引文件.tim来得到在索引文件.doc、.pos、pay的信息。
    注意term文件中按Field保存，每个Field中按PendingBlock(pendingBlock中的项有相同的前缀)保存数据，除了最后一个pendingBlock，其他的pendingBlock至少
包含25个词项(或sub pendingBlock)，最多不超过48个。设置最小值是为了防止频繁从磁盘加载pendingBlock，设置最大值是为了查询时减少从磁盘加载的数据量。
    注意只有PendingTerm有termStat和termMetaData。

2. 压缩
    如果平均后缀长度大于2且公共前缀长度大于2，会对后缀字节数组进行压缩。
    如果平均后缀长度大于2，会先尝试用LZ4压缩算法压缩，如果压缩后大小小于原来的3/4，压缩成功；否则，尝试下面的步骤。
    如果LZ4没有压缩成功，尝试用LowercaseAsciiCompression算法压缩（该算法对[0x1F,0x3F) or [0x5F,0x7F) 范围，即[31, 63)或[95, 127), 包含所有的数字，小写
字母，点，中划线和下划线, 压缩效果非常好）。如果压缩成功，保存；否则，使用原后缀字节数组。

3. SingletonDocId
    termStats中会保存singletonCount。
    termMetadata中会保存singletonCount。

4. termMetadata
    lastPosBlockOffset: prox个数不是128的倍数，最后一部分会使用VIntBlock保存在pos文件中，保存lastPosBlockOffset指向VIntBlock开始的FP

5. outerNode VS innerNode
    outerNode指只包含pendingTerm的PendingBlock，innerNode指至少包含一个pendingBlock的pendingBlock。
    innerNode中的PendingBlock不会保存termStats和termMetadata，会在SuffixLength中保存跳转到对应block的offset。
    通过Token区分是outerNode，innerNode

6. 优化点
    保存suffixLength时，如果所有的suffixLength都相等(不超过1byte)，只会保存第一个byte。【针对结构化数据，比如id】

@startuml
json ".tim File Layout \n 存储词典，如term后缀，term统计（docFreq，totalTermFreq），term元数据（该term在doc，pos，pay文件开始的FP，以及pos文件中VInt Block开始的FP，\n doc文件中skipList开始的offset）" as J {
   "Header":[
      {"HeaderMagic\t": "[Int] 0x3fd76c17"},
      {"Codec\t\t": "[String] BlockTreeTermsDict"},
      {"Version\t\t": "[Int] 0"},
      {"Id\t\t\t": "[16 Bytes] random id"},
      {"SuffixLength\t": "[Byte] 0x0A"},
      {"Suffix\t\t": "[Bytes] Lucene90_0"}
   ],
   "Content":[
      {"FieldA\t": [
         {"PostingsHeader\t": "..."},
         {"NodeBlocks\t\t": [
            {"OuterNode\t": [
               {"EntryCountCode\t": "[VInt] EntryCountCode << 1 | 1 if isLast else 0"},
               {"Token\t\t\t": "[VLong] sumSuffixBytesLen << 3 | 0x04 if outerNode else 0 | compressionAlg.code"},
               {"SuffixBytes [Bytes]\t": [
                  {"term1Suffix\t":[]},
                  {"term2Suffix\t":[]},
                  {"...\t\t\t":[]}
               ]},
               {"SuffixLengths\t\t": [
                  {"SuffixLengthsLen\t\t": {"[VInt] len << 1 | 1 if allByteEqual else 0":[]}},
                  {"SuffixLengths [VInts]\t": [
                     {"term1SuffixLen\t":[]},
                     {"term2SuffixLen\t":[]},
                     {"...\t\t\t\t":[]}
                  ]}
               ]},
               {"TermStats\t\t": [
                  {"TermStatsLen\t\t\t": "[VInt]"},
                  {"TermStats\t\t\t": [
                     {"term1Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     {"term2Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     {"singletonCount\t": "[VInt] ((singletonCount - 1) << 1) | 1"},
                     {"term5Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     "..."
                  ]}
               ]},
               {"TermMetadatas\t": [
                  {"MetadataSize\t\t\t": "[VInt]"},
                  {"TermMetadatas\t\t": [
                     {"term1Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     {"term2Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     "..."
                  ]}
               ]}
            ]},
            {"InnerNode\t": [
               {"EntryCountCode\t": "[VInt] EntryCountCode << 1 | 1 if isLast else 0"},
               {"Token\t\t\t": "[VLong] sumSuffixBytesLen << 3 | 0x04 if outerNode else 0 | compressionAlg.code"},
               {"SuffixBytes [Bytes]\t": [
                  {"term1Suffix\t":[]},
                  {"term2Suffix\t":[]},
                  {"block1Suffix\t":[]},
                  {"term3Suffix\t":[]},
                  {"...\t\t\t":[]}
               ]},
               {"SuffixLengths\t\t": [
                  {"SuffixLengthsLen\t\t": {"[VInt] len << 1 | 1 if allByteEqual else 0\t\t  ":[]}},
                  {"SuffixLengths [VInts]\t": [
                     {"term1SuffixLen\t": {"term1SuffixLen << 1\t\t":[]}},
                     {"term2SuffixLen\t": {"term2SuffixLen << 1\t\t":[]}},
                     {"block1SuffixLen\t": {"block1SuffixLen << 1 | 1\t":[]}},
                     {"block1_Offset\t\t": {"startFP - block.fp\t\t\t":[]}},
                     {"term3SuffixLen\t": {"term3SuffixLen << 1\t\t":[]}},
                     {"...\t\t\t\t\t\t\t\t\t\t  ":[]}
                  ]}
               ]},
               {"TermStats\t\t": [
                  {"TermStatsLen\t\t\t": "[VInt]"},
                  {"TermStats\t\t\t": [
                     {"term1Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     {"term2Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     {"term3Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     {"singletonCount\t": "[VInt] ((singletonCount - 1) << 1) | 1"},
                     {"term7Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     "..."
                  ]}
               ]},
               {"TermMetadatas\t": [
                  {"MetadataSize\t\t\t": "[VInt]"},
                  {"TermMetadatas\t\t": [
                     {"term1Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     {"term2Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     {"term3Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     "..."
                  ]}
               ]}
            ]},
            {"OuterNode\t": "..."},
            "..."
         ]}
      ]},
      {"FieldB\t":["..."]},
      "..."
   ],
   "Footer":[
      {"FooterMagic\t": "[Int] 0xc02893e8"},
      {"Zero\t\t\t": "[Int] 0"},
      {"CRC\t\t\t": "[Long] crc"}
   ]
}
@enduml
