1. tmd文件（term metadata, 词项元数据文件）
    tmd文件保存tip文件中FST的元数据，以及字段级别统计数据。

@startuml
json ".tmd File Layout" as J {
   "Header":[
      {"HeaderMagic\t\t": "[Int] 0x3fd76c17"},
      {"Codec\t\t\t": "[String] BlockTreeTermsMeta"},
      {"Version\t\t\t": "[Int] 0"},
      {"Id\t\t\t\t": "[16 Bytes] random id"},
      {"SuffixLength\t\t": "[Byte] 0x0A"},
      {"Suffix\t\t\t": "[Bytes] Lucene90_0"}
   ],
   "Content":[
      {"FieldNum\t": "[VInt]"},
      {"Fields\t\t": [
          {"FieldA\t": [
             {"FieldMeta": [
                {"FieldNO\t\t\t": "[VInt] 字段序号"},
                {"NumTerms\t\t": "[VLong] 该Field包含的term个数"},
                {"RootCodeLength\t": "[VInt] FST中根PendingBlock对应的value"},
                {"RootCode\t\t": "[Bytes] timFPDelta<<2 | hasTerms | isFloor"},
                {"TotalTermFreq\t": "[VLong] Optional，term的词项频率之和"},
                {"TotalDocFreq\t\t": "[VLong] term的文档频率之和"},
                {"DocsCardinality\t": "[VInt] 文档数"},
                {"StartTerm\t\t": {
                    "Length\t\t": {"[VInt]\t\t":[]},
                    "Content\t\t": {"[Bytes]\t\t":[]}
                }},
                {"EndTerm\t\t\t": {
                    "Length\t\t": {"[VInt]\t\t":[]},
                    "Content\t\t": {"[Bytes]\t\t":[]}
                }},
                {"IndexFP\t\t\t": "[VLong] 该Field的数据在tip文件中的FP"},
                {"FSTInfo\t\t\t": {
                    "Header\t":[
                        {"HeaderMagic\t": "[Int] 0x3fd76c17"},
                        {"Codec\t\t": "[String] FST"},
                        {"Version\t\t": "[Int] 8"}
                    ],
                    "EmptyOutput\t":[
                        {"Marker\t\t": "[Byte] 0 or 1"},
                        {"EmptyLen\t": "[VInt] Optional"},
                        {"EmptyOutput\t": "[Bytes] Optional"}
                    ],
                    "InputType\t": "[Byte] byte1/byte2/byte4",
                    "StartNode\t": "[VLong] FST开始节点偏移量",
                    "FstLength\t": "[VLong] Optional，FST字节数组大小"
                }},
                "..."
             ]}
          ]},
          {"FieldB\t":["..."]},
          "..."
      ]},
      {"IndexFP\t\t": "[Long]"},
      {"TermFP\t\t": "[Long]"}
   ],
   "Footer":[
      {"FooterMagic\t": "[Int] 0xc02893e8"},
      {"Zero\t\t\t": "[Int] 0"},
      {"CRC\t\t\t": "[Long] crc"}
   ]
}
@enduml