1. .pos文件
    pos文件主要保存term的position信息，对于不满128的payload，offset信息，也保存在pos文件中。

@startuml
json ".pos File Layout" as J {
   "Header":[
      {"HeaderMagic[Int]\t": "0x3fd76c17"},
      {"Codec[String]\t\t": "Lucene90PostingsWriterPos"},
      {"Version[Int]\t\t": "0"},
      {"Id[16 bytes]\t\t": "random id"},
      {"SuffixLength[byte]\t": "0x0A"},
      {"Suffix[bytes]\t\t": "Lucene90_0"}
   ],
   "Content":[
    {"FieldA\t": [
      {"Term1\t": [
         {"PackedBlock\t":[
            {"PackedPosDeltaBlock\t":[
               {"Token\t\t": "(numEs << 5) | bitsRequired"},
               {"PosDeltas\t": "bit packing"},
               {"Exceptions\t": "(eIdx, eInc) * numEs"}
            ]}
         ]},
         {"PackedBlock\t":["..."]},
         {"...\t\t\t":["..."]},
         {"VIntBlock\t\t":[
            {"VIntProxBlock\t\t\t": [
               {"ProxTuple\t":[
                  "PosDeltaCode",
                  "payloadLength",
                  "payloadBytes",
                  "offsetStartDeltaCode\t\t",
                  "offsetLength"
               ]},
               {"...\t\t\t":["..."]}
            ]}
         ]}
      ]},
      {"Term2\t": ["..."]},
      {"...\t\t": ["..."]}
    ]},
    {"FieldB\t":["..."]},
    {"...\t\t":["..."]}
   ],
   "Footer":[
      {"FooterMagic[Int]\t": "0xc02893e8"},
      {"Zero[Int]\t\t\t": "0"},
      {"CRC[Long]\t\t": "crc"}
   ]
}
@enduml
