1. .pos文件
    pos文件保存term的position信息，对于不满128的payload，offset信息，也保存在pos文件中。

@startuml
json ".pos File Layout" as J {
   "Header":[
      {"HeaderMagic\t": "[Int] 0x3fd76c17"},
      {"Codec\t\t": "[String] Lucene90PostingsWriterPos"},
      {"Version\t\t": "[Int] 0"},
      {"Id\t\t\t": "[16 Bytes] random id"},
      {"SuffixLength\t": "[Byte] 0x0A"},
      {"Suffix\t\t": "[Bytes] Lucene90_0"}
   ],
   "Content":[
    {"FieldA\t": [
      {"Term1\t": [
         {"PackedBlock\t":[
            {"PackedPosDeltaBlock\t":[
               {"Token\t\t": "[Byte] (numEs << 5) | bitsRequired\t"},
               {"PosDeltas\t": "[Longs] bit packing"},
               {"Exceptions\t": "[Bytes] (eIdx, eInc) * numEs"}
            ]}
         ]},
         {"PackedBlock\t":["..."]},
         "...",
         {"VIntBlock\t\t":[
            {"VIntProxBlock\t\t\t": [
               {"ProxTuple\t":[
                  "[VInt] PosDeltaCode",
                  "[VInt] payloadLength",
                  "[Bytes] payloadBytes",
                  "[VInt] offsetStartDeltaCode\t\t\t",
                  "[VInt] offsetLength"
               ]},
               "..."
            ]}
         ]}
      ]},
      {"Term2\t": ["..."]},
      "..."
    ]},
    {"FieldB\t":["..."]},
    "..."
   ],
   "Footer":[
      {"FooterMagic\t": "[Int] 0xc02893e8"},
      {"Zero\t\t\t": "[Int] 0"},
      {"CRC\t\t\t": "[Long] crc"}
   ]
}
@enduml
