1. .pay文件
    pay文件保存term的payload，offset信息。注意payload只保存packed block（即每128个），不满128的payload，offset保存在pos文件中。

@startuml
json ".pay File Layout" as J {
   "Header":[
      {"HeaderMagic\t": "[Int] 0x3fd76c17"},
      {"Codec\t\t": "[String] Lucene90PostingsWriterPay"},
      {"Version\t\t": "[Int] 0"},
      {"Id\t\t\t": "[16 Bytes] random id"},
      {"SuffixLength\t": "[Byte] 0x0A"},
      {"Suffix\t\t": "[Bytes] Lucene90_0"}
   ],
   "Content":[
    {"FieldA\t": [
      {"Term1\t": [
         {"PackedBlock\t":[
            {"PackedPayloadLenBlock\t":[
               {"Token\t\t\t": "[Byte] (numEs << 5) | bitsRequired\t"},
               {"payloadLens\t\t": "[Longs] bit packing"},
               {"Exceptions\t\t": "[Bytes] (eIdx, eInc) * numEs"}
            ]},
            "[VInt] SumPayloadLen",
            "[Bytes] PayloadBytes",
            {"PackedOffsetStartDeltaBlock":[
              {"Token\t\t\t": "[Byte] (numEs << 5) | bitsRequired\t"},
              {"OffsetStartDeltas\t": "[Longs] bit packing"},
              {"Exceptions\t\t": "[Bytes] (eIdx, eInc) * numEs"}
            ]},
            {"PackedOffsetLenBlock\t\t":[
              {"Token\t\t\t": "[Byte] (numEs << 5) | bitsRequired\t"},
              {"OffsetLens\t\t": "[Longs] bit packing"},
              {"Exceptions\t\t": "[Bytes] (eIdx, eInc) * numEs"}
            ]}
         ]},
         {"PackedBlock\t":["..."]},
         {"...\t\t\t":[]}
      ]},
      {"Term2\t": []},
      {"...\t\t": []}
    ]},
    {"FieldB\t":["..."]},
    {"...\t\t":["..."]}
   ],
   "Footer":[
      {"FooterMagic\t": "[Int] 0xc02893e8"},
      {"Zero\t\t\t": "[Int] 0"},
      {"CRC\t\t\t": "[Long] crc"}
   ]
}
@enduml
