
@startuml
json ".tip File Layout" as J {
   "Header":[
      {"HeaderMagic\t": "[Int] 0x3fd76c17"},
      {"Codec\t\t": "[String] BlockTreeTermsIndex"},
      {"Version\t\t": "[Int] 0"},
      {"Id\t\t\t": "[16 Bytes] random id"},
      {"SuffixLength\t": "[Byte] 0x0A"},
      {"Suffix\t\t": "[Bytes] Lucene90_0"}
   ],
   "Content":[
      {"FieldA\t": [
         {"PostingsHeader\t": "..."},
         {"NodeBlocks\t\t": [
            {"OuterNode\t": [
               {"EntryCountCode\t": "[VInt] EntryCountCode << 1 | 1 if isLast else 0"},
               {"Token\t\t\t": "[VLong] sumSuffixBytesLen << 3 | 0x04 if outerNode else 0 | compressionAlg.code"},
               {"SuffixBytes [Bytes]\t": [
                  "term1Suffix",
                  "term2Suffix",
                  "..."
               ]},
               {"SuffixLengths\t\t": [
                  {"SuffixLengthsLen\t\t": "[VInt] len << 1 | 1 if allByteEqual else 0"},
                  {"SuffixLengths [VInts]\t": [
                     "term1SuffixLen",
                     "term2SuffixLen",
                     "..."
                  ]}
               ]},
               {"TermStats\t\t": [
                  {"TermStatsLen\t\t\t": "[VInt]"},
                  {"TermStats\t\t\t": [
                     {"term1Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     {"term2Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df"}
                     ]},
                     {"singletonCount\t": "[VInt] ((singletonCount - 1) << 1) | 1"},
                     {"term5Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df"}
                     ]},
                     "..."
                  ]}
               ]},
               {"TermMetadatas\t": [
                  {"MetadataSize\t\t\t": "[VInt]"},
                  {"TermMetadatas\t\t": [
                     {"term1Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     {"term2Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     "..."
                  ]}
               ]}
            ]},
            {"InnerNode\t": [
               {"EntryCountCode\t": "[VInt] EntryCountCode << 1 | 1 if isLast else 0"},
               {"Token\t\t\t": "[VLong] sumSuffixBytesLen << 3 | 0x04 if outerNode else 0 | compressionAlg.code"},
               {"SuffixBytes [Bytes]\t": [
                  "term1Suffix",
                  "term2Suffix",
                  "block1Suffix",
                  "term3Suffix",
                  "..."
               ]},
               {"SuffixLengths\t\t": [
                  {"SuffixLengthsLen\t\t": "[VInt] len << 1 | 1 if allByteEqual else 0"},
                  {"SuffixLengths [VInts]\t": [
                     {"term1SuffixLen\t": "term1SuffixLen << 1"},
                     {"term2SuffixLen\t": "term2SuffixLen << 1"},
                     {"block1SuffixLen\t": "block1SuffixLen << 1 | 1"},
                     {"block1_Offset\t\t": "startFP - block.fp"},
                     {"term3SuffixLen\t": "term3SuffixLen << 1"},
                     "..."
                  ]}
               ]},
               {"TermStats\t\t": [
                  {"TermStatsLen\t\t\t": "[VInt]"},
                  {"TermStats\t\t\t": [
                     {"term1Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df\t"}
                     ]},
                     {"term2Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df"}
                     ]},
                     {"term3Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df"}
                     ]},
                     {"singletonCount\t": "[VInt] ((singletonCount - 1) << 1) | 1"},
                     {"term7Stat\t\t": [
                        {"docFreq\t\t\t": "[VInt] df << 1"},
                        {"totalTermFreq\t": "[VLong] ttf - df"}
                     ]},
                     "..."
                  ]}
               ]},
               {"TermMetadatas\t": [
                  {"MetadataSize\t\t\t": "[VInt]"},
                  {"TermMetadatas\t\t": [
                     {"term1Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     {"term2Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     {"term3Meta\t": [
                        {"docStartFP\t\t": "[VLong] delta"},
                        {"SingletonDocId\t": "[VInt] optional\t"},
                        {"posStartFP\t\t": "[VLong] delta"},
                        {"payStartFP\t\t": "[VLong] delta"},
                        {"lastPosBlockOffset\t": "[VLong]"},
                        {"skipOffset\t\t": "[VLong]"}
                     ]},
                     "..."
                  ]}
               ]}
            ]},
            {"OuterNode\t": "..."},
            "..."
         ]}
      ]},
      {"FieldB\t":["..."]},
      "..."
   ],
   "Footer":[
      {"FooterMagic\t": "[Int] 0xc02893e8"},
      {"Zero\t\t\t": "[Int] 0"},
      {"CRC\t\t\t": "[Long] crc"}
   ]
}
@enduml